apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    kind: ReplicaSet
    name: nginx-rs
  targetCPUUtilizationPercentage: 80
