apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: 256m
            memory: 100Mi
        ports:
        - containerPort: 80
